spring:
  datasource:
    driverClassName: org.h2.Driver
    password: yunus123
    username: yunus515
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8090